### PR TITLE
Feature/forgotten password jim

### PR DESCRIPTION
**Pull request by remarcmij**
Hi @Meno-101, let's discuss these changes in an online session when you have time.

### CODE REVIEW

**Comment by Meno-101** [comment]
yes, do you have any preference?

**Comment by remarcmij** [comment]
We can do it tomorrow, say 14:30? Or any time tomorrow. This Sunday I have other commitments.

**Comment by Meno-101** [comment]
Yes that would be amazing 🙂

**Comment by remarcmij** [comment]
No longer needed

**Pull request closed without merging**
